name: Link Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install lychee
        uses: lycheeverse/lychee-action@v1.10.1
        with:
          args: --verbose --no-progress --config ./lychee.toml ./public ./data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
